// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brand.sniffy.bo.core.model;

import com.brand.sniffy.bo.core.model.SearchRequest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SearchRequest_Roo_Configurable {
    
    declare @type: SearchRequest: @Configurable;
    
}
