// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.brand.application.bo.core.model;

import com.brand.application.bo.core.model.ComponentRating;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ComponentRating_Roo_Configurable {
    
    declare @type: ComponentRating: @Configurable;
    
}
